In [1]:
import torch

### intro

In [2]:
# arange

x = torch.arange(0,12,dtype=torch.float32)
x


# torch.arange(start, end, step=1, dtype=None, device=None)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
# We can inspect the total number of elements in a tensor via its numel method
x.numel()

12

In [4]:
# size of tensor along each dimension
x.shape

torch.Size([12])

In [5]:
# it can reshape changes the shape of a tensor without changing its data or 
# total number of elements
X = x.reshape(3,-1)
print(X)
X.shape


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


torch.Size([3, 4])

In [6]:
# We can construct a tensor with all elements set to 0 and a shape via the zeros function
torch.zeros((2,3,4)) 

# torch.zeros((2,3,4)) 2 block(batch size), 3 rows, 4 column 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# We can construct a tensor with all elements set to 0 and a shape via the ones function
torch.ones((2,3,4)) 

# torch.zeros((2,3,4)) 2 block(batch size), 3 rows, 4 column 

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# We often wish to sample each element randomly (and independently) from a given probability distribution. 
# For example, the parameters of neural networks are often initialized randomly. 
# The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.

torch.randn(3,4)

tensor([[ 0.8801,  0.1775,  1.0506,  1.3037],
        [ 2.1808, -0.9400,  0.0440, -0.2538],
        [ 1.1615,  1.0196,  1.1490,  0.4256]])

In [9]:
# we can construct matrix from list of list and it called tensor

torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Indexing and Slicing



In [10]:
# we can access tensor elements by indexing

# inex start from 0,1,2,3 inside square bracket

# tensor([[ 0.,  1.,  2.,  3.],
#         [ 4.,  5.,  6.,  7.],
#         [ 8.,  9., 10., 11.]])

# e.g., X[start:stop]

X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [11]:
# we can also write elements of a matrix by specifying indices.
X[1,2] = 17 # in 1st row 2nd column index it replaces as 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
# we want to assign multiple elements the same value,

# For instance, [:2, :] accesses the first and second rows,
# where : takes all the elements along axis 1 (column). 

X[:2, :]  = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### Operation

In [13]:
# computes e^x eulers rule  e = 2.71828 
torch.exp(x)


tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

A function f : ℝ × ℝ → ℝ maps two real numbers to one real number.
If u and v are vectors of the same shape, we can lift f to a vector function F, producing a vector c where each element is computed using standard arithmetic operations element-wise.

In [14]:
x= torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])

x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
# We can also concatenate multiple tensors
# it joins tensors together along a given dimension.
# cat does NOT add, multiply, or average
# It sticks tensors together.Think of it like gluing arrays.

X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

torch.cat((X,Y),dim=0) ,torch.cat((X,Y),dim=1)

# dim=0 (row-wise / vertical) 
# dim=1 (column-wise / horizontal) 

# If X and Y both have shape (a, b):
# cat(dim=0) → (a + a, b)
# cat(dim=1) → (a, b + b)

# Result (dim=0):
# [ 0  1  2  3 ]
# [ 4  5  6  7 ]
# [ 8  9 10 11 ]
# [ 2  1  4  3 ]
# [ 1  2  3  4 ]
# [ 4  3  2  1 ]

# Result (dim=1):

# [ 0  1  2  3 | 2  1  4  3 ]
# [ 4  5  6  7 | 1  2  3  4 ]
# [ 8  9 10 11 | 4  3  2  1 ]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
#  to check each postion are equal
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
# Summing all the elements in the tensor yields a tensor with only one element.
X.sum()

tensor(66.)

### Broadcasting


In [18]:
# even when shapes differ, 
# we can still perform elementwise binary operations by invoking the broadcasting mechanism.

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a,b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
# even a and b are 3 x 1 ,1 x 2 matrices,
# their shapes do not match up. Broadcasting produces a larger 3 x 2 
# matrix by replicating matrix a along the columns and matrix b along the rows before adding them elementwise.
a+b,a-b,a*b

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[ 0, -1],
         [ 1,  0],
         [ 2,  1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]))

### saving memory

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

# Python first evaluates Y + X, allocating new memory for the result and then points Y to this new location in memory.

False

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

# To illustrate this concept, we overwrite the values of tensor Z,
# after initializing it, using zeros_like, to have the same shape as Y.

id(Z): 2277899099728
id(Z): 2277899099728


In [22]:
before = id(X)
X += Y
id(X) == before

True

### Conversion to python other objects

In [ ]:
# Converting to a NumPy tensor (ndarray), or vice versa
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

# NumPy doesn’t understand GPU
# NumPy doesn’t track gradients
# Prevents silent bugs in backprop

(numpy.ndarray, torch.Tensor)

In [ ]:
# To convert a size-1 tensor to a Python scalar, 
# we can invoke the item function or Python’s built-in functions.
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)